version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3
    steps:
      - checkout
      - run: pip install -e .
      - run: pip install pytest
      - run: pytest
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
